import { UPDATE } from "@ngrx/store";

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/Auth/login',
    REGISTER: '/Auth/register',
    FORGET_PASSWORD: '/Auth/ForgetPassword',
    VERIFY_FORGET_PASSWORD: '/Auth/VerifyForgetPassword',
    PROFILE_UPDATE: '/Auth/ProfileUpdate',
    PROFILE_DETAILS: '/Auth/ProfileDetails',
    CHANGE_PASSWORD: '/Auth/ResetPassword',
    HOMEPAGE_CONTENT: '/Auth/HomePageContent',
    IMPERSONATE: '/Auth/ImpersonateCompany',
  },

  USERS: {
    CREATE: '/User/Create',
    UPDATE: '/User/Update',
    DELETE: '/User/Delete',
    ACTIVE_INACTIVE: '/User/ActiveInActive',
    GET_ALL: '/User/GetAll',
  },

  ROLE: {
    CREATE: '/Role/Create',
    UPDATE: '/Role/Update',
    DELETE: '/Role/Delete',
    ACTIVE_INACTIVE: '/Role/ActiveInActive',
    GET_ALL: '/Role/GetAll',
  },

  COMMON_API: {
    GET_ALL_TENANT : '/Common/GetAllTenant',
    GET_ALL_ROLES: '/Common/GetAllRoles',
    GET_ALL_NOTIFICATION: '/Common/GetAllNotification',
    GET_ALL_FARMS: '/Common/GetAllFarm',
    GET_ALL_FEED: '/Common/GetAllFeed',
    GET_ALL_Days: '/Common/GetAllDay',
    GET_ALL_ANIMALTYPE: '/Common/GetAllAnimalType',
    GET_ALL_ANIMAL_LACTATION: '/Common/GetAllAnimalLactation',
    GET_ALL_ANIMAL_GROUP: '/Common/GetAllAnimalGroup',
    GET_RATION_ITEMS: '/Common/GetRationByRationd',
    GET_TEMPLATE_CATEGORY: '/Common/GetAllTemplateCategory',
    GET_TEMPLATE_PLACEHOLDER: '/Common/GetAllPlaceholder',
    GET_RATION: '/Common/GetAllRation',
    GET_OPERATOR: '/Common/GetAllOperator',
    GET_OPERATORS_AND_RATIONS: '/Common/GetAllOperatorAndRation',
    GET_ANIMALGROUPS_BY_FARM_ID: '/Common/GetAnimalGroupByFarmId',
    GET_FEEDS_BY_FARM_ID: '/Common/GetFeedByFarmId',
    GET_PLACEHOLDER_BY_CATEGORY_ID: '/Common/GetAllPlaceholderByCategoryId',
    GET_ALL_FORMULA_LIST: '/Common/GetAllFormula',
    GET_Language_LIST: '/Common/GetAllLanguage',
    MARK_ALL_READ_NOTIFICATION: '/Common/ReadAllNotification',
    UPDATE_NOTIFICATION: '/Common/UpdateNotification',
    GET_ALL_SUPPLIER_LIST: '/Common/GetAllSupplier',
    GET_ALL_MATERIAL_BY_SUPPLIER_ID: '/Supplier/GetAllSupplierPrice',
    GET_OPERATORS_AND_MATERIAL: '/Common/GetAllOperatorAndMaterial',
    GET_PRODUCT: '/Common/GetAllProduct',
    GET_ALL_MATERIAL_BY_SUPPLIER_ID_IN_FORMULA: '/Common/GetAllMaterialBySupplierId',
    GET_ALL_PRODUCT_BY_SUPPLIER_ID: '/Common/GetAllProductBySupplierId',
    GET_ALL_FORMULA_BY_SUPPLIER_ID: '/Common/GetAllFormulaBySupplierId'
  },

  Module: {
    GET_ALL: '/Module/modules',
    GET_ALL_ROLES: '/Common/GetAllRoles',
    CREATE: '/Module/Add',
    DELETE: '/Module/Delete',
    UPDATE: '/Module/Edit',
  },

  Tenant: {
    GET_ALL: '/Tenant/GetAll',
    CREATE: '/Tenant/Create',
    UPDATE: '/Tenant/Update',
    DELETE: '/Tenant/Delete',
    ACTIVE_INACTIVE: '/Tenant/ActiveInActive',
  },

  FARM: {
    CREATE: '/Farm/Create',
    UPDATE: '/Farm/Update',
    DELETE: '/Farm/Delete',
    ACTIVE_INACTIVE: '/Farm/ActiveInActive',
    GET_ALL: '/Farm/GetAll',
  },
  RATION: {
    CREATE: '/Ration/Create',
    UPDATE: '/Ration/Update',
    DELETE: '/Ration/Delete',
    ACTIVE_INACTIVE: '/Ration/ActiveInActive',
    GET_ALL: '/Ration/GetAll',
  },
  FEED: {
    CREATE: '/Feed/Create',
    UPDATE: '/Feed/Update',
    DELETE: '/Feed/Delete',
    ACTIVE_INACTIVE: '/Feed/ActiveInActive',
    GET_ALL: '/Feed/GetAll',
  },
  KPI: {
    CREATE: '/Kpi/Create',
    UPDATE: '/Kpi/Update',
    DELETE: '/Kpi/Delete',
    ACTIVE_INACTIVE: '/Kpi/ActiveInActive',
    GET_ALL: '/Kpi/GetAll',
  },
  CALVES: {
    CREATE: '/Calves/Create',
    UPDATE: '/Calves/Update',
    DELETE: '/Calves/Delete',
    ACTIVE_INACTIVE: '/Calves/ActiveInActive',
    GET_ALL: '/Calves/GetAll',
  },

  AnimalType: {
    CREATE: '/Animal/CreateAnimalType',
    UPDATE: '/Animal/UpdateAnimalType',
    DELETE: '/Animal/DeleteAnimalType',
    ACTIVE_INACTIVE: '/Animal/ActiveInactiveAnimalType',
    GET_ALL: '/Animal/GetAllAnimalType',
  },

  AnimalLactation: {
    CREATE: '/Animal/CreateAnimalLactation',
    UPDATE: '/Animal/UpdateAnimalLactation',
    DELETE: '/Animal/DeleteAnimalLactation',
    ACTIVE_INACTIVE: '/Animal/ActiveInactiveLactation',
    GET_ALL: '/Animal/GetAllLactation',
  },
  AnimalGroup: {
    CREATE: '/Animal/CreateAnimalGroup',
    UPDATE: '/Animal/UpdateAnimalGroup',
    DELETE: '/Animal/DeleteAnimalGroup',
    ACTIVE_INACTIVE: '/Animal/ActiveInactiveAnimalGroup',
    GET_ALL: '/Animal/GetAllAnimalGroup',
  },
  COMPANY: {
    UPDATE: '/Common/UpdateSettingById',
    GET_BY_ID: '/Common/SettingById',
  },
  CONFIGURATION: {
    UPDATE: '/Configuration/AddOrUpdateEmailConfiguration',
    GET_CONFIGURATION: '/Configuration/GetEmailConfiguration',
  },
  TemplateCategory: {
    CREATE: '/TemplateCategory/Create',
    UPDATE: '/TemplateCategory/Update',
    DELETE: '/TemplateCategory/Delete',
    ACTIVE_INACTIVE: '/TemplateCategory/ActiveInActive',
    GET_ALL: '/TemplateCategory/GetAll',
  },

  Template: {
    CREATE: '/Template/Create',
    UPDATE: '/Template/Update',
    DELETE: '/Template/Delete',
    ACTIVE_INACTIVE: '/Template/ActiveInActive',
    GET_ALL: '/Template/GetAll',
  },
  OPERATOR: {
    CREATE: '/Operator/Create',
    UPDATE: '/Operator/Update',
    DELETE: '/Operator/Delete',
    ACTIVE_INACTIVE: '/Operator/ActiveInActive',
    GET_ALL: '/Operator/GetAll',
  },
  PLACEHOLDER: {
    CREATE: '/PlaceHolder/Create',
    UPDATE: '/PlaceHolder/Update',
    DELETE: '/PlaceHolder/Delete',
    ACTIVE_INACTIVE: '/PlaceHolder/ActiveInActive',
    GET_ALL: '/PlaceHolder/GetAll',
  },
  PLACEHOLDERS_MAPPING: {
    CREATE: '/PlaceholderMapping/Create',
    UPDATE: '/PlaceholderMapping/Update',
    DELETE: '/PlaceholderMapping/Delete',
    ACTIVE_INACTIVE: '/PlaceholderMapping/ActiveInActive',
    GET_ALL: '/PlaceholderMapping/GetAll',
  },
  FORMULA: {
    CREATE: '/Formula/Create',
    UPDATE: '/Formula/Update',
    DELETE: '/Formula/Delete',
    ACTIVE_INACTIVE: '/Formula/ActiveInActive',
    GET_ALL: '/Formula/GetAll',
    VALIDATE_FORMULA: '/Ration/ValidateFormula',
  },
  TECHNICAL_REPORT: {
    CREATE: '/Ration/SaveTechnicalRecord',
    UPDATE: '/TechnicalReport/Update',
    DELETE: '/TechnicalReport/Delete',
    ACTIVE_INACTIVE: '/TechnicalReport/ActiveInActive',
    GET_ALL: '/TechnicalReport/GetAll',
    GET_TECHNICAL_REPORT: '/Ration/GetByEconomicReport',
  },
  LANGUAGE: {
    CREATE: '/Language/Create',
    UPDATE: '/Language/Update',
    DELETE: '/Language/Delete',
    ACTIVE_INACTIVE: '/Language/ActiveInActive',
    GET_ALL: '/Language/GetAll',
    Export: '/Language/ExportLanguageExcel',
    Import: '/Language/ImportLanguageExcel',
    LanguageByCulture: '/Language/LanguageByCulture',
  },
  DASHBOARD: {
    GET_DASHBOARD_DATA: '/Dashboard/DashboardData',
    GET_COMPANY_DASHBOARD: '/Dashboard/CompanyDashboard',
    GET_AGGREGATED_ANALYTICS: '/Dashboard/AggregatedAnalytics',
    GET_AGGREGATED_ARCHIVE: '/Dashboard/AggregatedArchive',
    GET_AGGREGATED_REPORT: '/Dashboard/AggregatedReport',
    GET_COMPANY_ARCHIVE: '/Dashboard/CompanyArchive',
    GET_COMPANY_REPORT: '/Dashboard/CompanyReport',
    EXPORT_COMPANY_REPORT_PDF: '/Dashboard/CompanyReportExportPdf',
    EXPORT_AGGREGATED_REPORT_PDF: '/Dashboard/AggregatedReportExportPdf',
    EXPORT_AGGREGATED_REPORT_CSV: '/Dashboard/AggregatedReportExportCsv',
    UPDATE_COMPANY_ARCHIVE: '/Dashboard/CompanyArchiveUpdate',
  },

  SUPPLIER: {
    CREATE: '/Supplier/Create',
    UPDATE: '/Supplier/Update',
    DELETE: '/Supplier/Delete',
    ACTIVE_INACTIVE: '/Supplier/ActiveInActive',
    GET_ALL: '/Supplier/GetAll',
    GENERATE_SUPPLIER_CODE: '/Supplier/GenerateSupplierCode',
  },

  MATERIAL: {
    CREATE: '/Material/Create',
    UPDATE: '/Material/Update',
    DELETE: '/Material/Delete',
    ACTIVE_INACTIVE: '/Material/ActiveInActive',
    GET_ALL: '/Material/GetAll',
    GENERATE_SUPPLIER_CODE: '/Material/GenerateMaterialCode',
     IMPORTMATERIAL: '/Material/ImportMaterials',
  EXPORTMATERIAL: '/Material/ExportMaterials',
  },

  PRODUCT: {
    CREATE: '/Product/Create',
    UPDATE: '/Product/Update',
    DELETE: '/Product/Delete',
    ACTIVE_INACTIVE: '/Product/ActiveInActive',
    GET_ALL: '/Product/GetAll',
    GENERATE_PRODUCT_CODE: '/Product/GenerateProductCode',
  },

  SUPPLIERPRICE: {
    CREATE_OR_UPDATE: '/Supplier/UpdateSupplierPrice',
    UPDATE: '/SupplierPrice/Update',
    DELETE: '/SupplierPrice/Delete',
    ACTIVE_INACTIVE: '/SupplierPrice/ActiveInActive',
    GET_ALL: '/SupplierPrice/GetAll',
    GENERATE_SUPPLIER_CODE: '/SupplierPrice/GenerateSupplierCode',
    BULK_SAVE: '/SupplierPrice/BulkSave',
  },

  SUPPLIER_PRICE_FORMULA: {
    CREATE: '/MstFormula/Create',
    UPDATE: '/MstFormula/Update',
    DELETE: '/MstFormula/Delete',
    ACTIVE_INACTIVE: '/MstFormula/ActiveInActive',
    GET_ALL: '/MstFormula/GetAll',
    VALIDATE_FORMULA: '/MstFormula/Validate',
    
  },

   CALFBARN: {
    CREATE: '/CalfBarn/Create',
    UPDATE: '/CalfBarn/Update',
    DELETE: '/CalfBarn/Delete',
    ACTIVE_INACTIVE: '/CalfBarn/ActiveInActive',
    GET_ALL: '/CalfBarn/GetAll',
  },
   PRICINGSETTING: {
    UPDATE: '/PricingSetting/Add',
    GET_ALL: '/PricingSetting/GetAll',
  },
   PRODUCTPRICING: {
    CREATE: '/ProductPricing/Create',
    GET_ALL: '/ProductPricing/GetAll',
    UPDATE: '/ProductPricing/Update',
    ACTIVE_INACTIVE: '/ProductPricing/ActiveInActive',
    DELETE: '/ProductPricing/Delete',
    GET_PREVIOUS_PRICE: '/ProductPricing/GetPreviousPrice',
  },

  PRODUCT_BUILD: {
    CREATE: '/ProductBuild/Create',
    UPDATE: '/ProductBuild/Update',
    DELETE: '/ProductBuild/Delete',
    ACTIVE_INACTIVE: '/ProductBuild/ActiveInActive',
    GET_ALL: '/ProductBuild/GetAll',
    GENERATE_SUPPLIER_CODE: '/Supplier/GenerateSupplierCode',
    GET_BY_ID: '/ProductBuild/GetById',
  },
};
