export interface PaginationRequest {
  tenantId: string;
  searchValue: string;
  orderStatus: string;
  notificationType: string;
  pageNo: number;
  recordPerPage: number;
  startDate: string | null;
  expiryDate: string | null;
  toDate: string | null;
  formDate: string | null;
  status: string | "";
  vendor: string;
  isOptionExpression: boolean;
  isPartnerEstimateInvoice: boolean;
  isCustomer: boolean;
  customerId: string;
  estimationId: string;
  orderId: string;
  productType: string;
  jobStatus: string;
  jobId: string;
  address: string;
  region: string;
  sortColumn: string;
  sortDirection: string;
  columnFilters: { field: string; value: string }[];
  live: boolean;
  estimateCode: string;
  orderUniqueCode: string;
  isMasterData: boolean;
}
